### PR TITLE
Fix and Update Unreal Plugin for UE 5

### PR DESCRIPTION
**Pull request by JBenda**
Inkcpp got many new features which are not mirrored in the Unreal Plugin. On top, many small name clashes with UE5 exists.

* [x] apply changes from #35
* [x] Fix compiler errors
* [x] adopt all output functions to `basic_stream::get()` atoutput.cpp:142
* [x] loading .ink files directly
* [ ] revisit Plugin Design to introduce new concepts and use UE5 Nodes system 
  * [x] Snapshot store and load
  * [ ] read and modify lists variables
* [x] merging pending PRs

### CODE REVIEW

**Comment by JBenda** [comment]
So the unreal plugin is reworked:
* adapted to UE5, but should also work with UE4.27 (not tested)
* added an example level + assets (contained in attachments)

Please feel free to test it and give feedback :)

Instructions:
1. create an unreal project and close it
2. not down path to unreal project (PATH/TO/UNERAL_PROJECT) e.g. D:\Dokumente\Unreal Projects\InkDemo
3. `git clone https://github.com/brwarner/inkcpp.git`
4. `cd inkcpp`
5. `mkdir build`
6. `mkdir plugin`
7. `cd build`
8. `cmake -DCMAKE_INSTALL_PREFIX=../plugin ..`
9. `cmake --install . --component unreal`
10. compile plugin:
      `\PATH\TO\UNREAL_ENGINE\Build\BatchFiles\RunUAT.bat BuildPlugin -plugin="PATH\TO\GIT\REPO\plugin\inkcpp\inkcpp.uplugin" -package="\PATH\TO\UNERAL_PROJECT\Plugins\inkcpp" -TargetPlatforms=Win64`
11. Start unreal project
12. load assets
13. start level, for the control use the 1,2,3 and 4 Key to select the corresponding choice

* in the main world is a MyInkRuntime instance which takes a InkAsset for the story to play
    * unreal_example shows different kind of interaction between engine and ink
    * TheInterceptor is a larger example story from ink
* to create a InkAsset import a `.ink.` file or an inklecate compiled `.json` ← we will probably not in future keep high priority on json imports ...

[UnrealAssets.zip](https://github.com/brwarner/inkcpp/files/9227702/UnrealAssets.zip)

**Comment by JBenda** [comment]
So the unreal plugin is reworked:
* adapted to UE5, but should also work with UE4.27 (not tested)
* added an example level + assets (contained in attachments)


Last Update: 20.09.2022

Please don't hesitate to test it and provide feedback :)

Instructions:
1. create an unreal project and close it
2. not down path to unreal project (PATH/TO/UNERAL_PROJECT) e.g. D:\Dokumente\Unreal Projects\InkDemo
3. `git clone --branch feature/Unreal_fixes https://github.com/JBenda/inkcpp.git`
4. `cd inkcpp`
5. `mkdir build`
6. `mkdir plugin`
7. `cd build`
8. `cmake -DCMAKE_INSTALL_PREFIX=../plugin ..`
9. `cmake --install . --component unreal`
10. compile plugin:
      `\PATH\TO\UNREAL_ENGINE\Build\BatchFiles\RunUAT.bat BuildPlugin -plugin="PATH\TO\GIT\REPO\plugin\inkcpp\inkcpp.uplugin" -package="\PATH\TO\UNERAL_PROJECT\Plugins\inkcpp" -TargetPlatforms=Win64`
11. Copy content of the InkUnrealExample in PATH\TO\UNREAL_PROJECT\Content
    grafik
13. Start unreal project
14. Select Level `NewMap` from the Content Drawer
15. start level, for the control use the 1,2,3 and 4 Key to select the corresponding choice

* in the main world is a MyInkRuntime instance which takes a InkAsset for the story to play
    * unreal_example shows different kind of interaction between engine and ink
    * TheInterceptor is a larger example story from ink
* to create a InkAsset import a `.ink.` file or an inklecate compiled `.json` ← we will probably not in future keep high priority on json imports ...

A Record of the terminal side of the build process can be found [here](https://asciinema.org/a/516830)
[InkAssets-v2.zip](https://easyupload.io/6ripxb)

**Comment by sinbad** [comment]
I'm just checking this PR out because I'm investigating Ink in UE5, but I think the attachment for "InkUnrealExample" is missing?

**Comment by JBenda** [comment]
### Merged Snapshot (Save/Load) Functionality

Namely, a new function for the `InkRuntime` was added `InkSnapshot Snapshot()` this creates a snapshot which can then be loaded with `LoadSnapshot(InkSnapshot)`.

Be aware that loading a snapshot invalidates all existing Threads, so best stop them or reinitialize them with `StartExisting()`.

A snapshot contains all corresponding Threads of the Runtime. Currently, you create new threads in the same order they were created before, later a label feature should be introduced.

Feel free to try, and comment if you have any input.

PS: A Unreal example Project which uses the new functionality can be fond below. For the instructions, please refer to the post before.

[Extended Example](https://cloud.julian-benda.de/index.php/s/BDx7LDX7nECSY4j)

**Comment by sandiz** [comment]
ink compiler 1.1.1 is no longer able to compile TagsStory.ink / all tags tests are failing as inklecate is not able to compile ink files.

image

```
/Users/sandi/Projects/inkcpp/cmake-build-release/inkcpp_test/inkcpp_test -r xml -d yes --order lex
Testing started at 2:29 AM ...

/Users/sandi/Projects/inkcpp/inkcpp_test/Tags.cpp:145: Failure:
due to unexpected exception with message:
  Diverting past end of story data!




ERROR: 'TagsStory.ink' line 9: Expected end of line but saw '# choice_tag_b'
ERROR: 'TagsStory.ink' line 21: Expected end of line but saw '# close_tag'

/Users/sandi/Projects/inkcpp/inkcpp_test/Tags.cpp:46: Failure:
due to unexpected exception with message:
  Inklecate failed with exit code 256



/Users/sandi/Projects/inkcpp/inkcpp_test/Tags.cpp:31: Failure:
due to unexpected exception with message:
  Unrecognized command!


/Users/sandi/Projects/inkcpp/inkcpp_test/Tags.cpp:179: Failure:
due to unexpected exception with message:
  Unrecognized command!


Process finished with exit code 4

```
Any pointers on how to fix this ?

**Comment by JBenda** [comment]
Looks like they changed the syntax. It seems the tag must now be in front of the jump.
I will take a deeper look on Monday.

```
+ Hey # choice_tag
   -> knot2
```

**Comment by JBenda** [comment]
The notation with `* [b # choice_tag_b]->knot2` results in the expected output for inky. Sadly, it also introduced a new tag, which is not yet supported by us. But WIP ^^

**Comment by sandiz** [comment]
Thanks so much for pushing a fix @JBenda 🙏 🎉 , i'll test this soonish™ and get back! 

is there a patreon or github sponsor option available ? would love to support you guys! ❤️

**Comment by sandiz** [comment]
tested on mac / windows - inkcpp is working correctly (cpp library) with latest inklecate v1.1.1

**Comment by JBenda** [comment]
> Thanks so much for pushing a fix @JBenda pray tada , i'll test this ~soonish™~ and get back! is there a patreon or github sponsor option available ? would love to support you guys! heart

There is no `inkcpp` patreon, but please don't hesitate to use GitHub [sponsoring](https://github.com/sponsors/JBenda)

**Pull request merged**
