### PR TITLE
Ink Proof Badge Generation

### PR DESCRIPTION
**Pull request by brwarner**
Trying to get Github CI to generate one badge per operating system that prints the inkproof test results.

### CODE REVIEW

**Comment by brwarner** [comment]
Not sure why the `cp` command with the `*` is failing on Windows. The `ls` command right before it says there's something in the directory... Probably missing something.

**Comment by JBenda** [comment]
`cp: cannot stat 'D:\a\inkcpp\inkcpp/build/bin/*': No such file or directory`
I think this is the Problem, because Windows usese `\` instead of `/` you try to copy the file `"inkcpp/build/bin/*"` in directory `::\a\inkcpp`

**Comment by brwarner** [comment]
I have it set to use the bash shell though. Hrm. I'll give it a shot.

**Comment by brwarner** [comment]
So this runs now but I think the badge action I'm using is busted. The urls lead to server errors. Also would be nice if all the bot comments were merged into one. I'll improve soon.

**Comment by JBenda** [comment]
Cool that it's start working :)

but why only 96 inkproofs? they should be a little over 100.

**Comment by brwarner** [comment]
Implemented this better using the sticky comment action in another branch.

**Pull request closed without merging**
