### PR TITLE
inkcpp_test build error on M1/arm64

### PR DESCRIPTION
**Pull request by JBenda**
Update Catch dependency to fix compile error

### CODE REVIEW

**Comment by brwarner** [comment]
I think the fail is caused by some kind of permission issue. Let's see if it works when I re-trigger the jobs.

**Comment by brwarner** [comment]
This is a known GitHub issue when issuing PRs from a fork. 

https://github.com/actions/first-interaction/issues/10

The failing action is trying to post a comment on this PR with the inkproof results but since it's running from a fork, the environment is read-only (despite the fact you're a collaborator on this project).

Anyway, the builds are passing so that's good.

**Comment by JBenda** [comment]
Then we just need to verify that this fixes  the compilation error for M1/arm64 chips.

**Comment by JBenda** [comment]
* Update Catch to work on M1/arm64
* fix Warning from macOS compiler about wrong initialization order
* disable "Pull Request Report" for PRs from forks

**Review by brwarner — APPROVED** [review]

**Pull request merged**
